---
- hosts: all
  gather_facts: no
  tasks:
  - name: Update Root user's Password
    user: 
      name: root
      update_password: always 
      password: $6$rounds=656000$jlI4oHwbLqbuzrOu$mHOs/JBJsXlaezr5wMZD5BY02XSY7S.9MFBGENmoaXF1SYXxqWzhu5LVJIQm3FTYeYV3GxUb3cZGF4sFswGgG0
